name: flutter_interview_questions
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  go_router: ^6.5.7
  flutter_gen: ^5.3.0
  kartal: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

  flutter_gen_runner: ^5.3.0
  build_runner: ^2.3.3


flutter:


  uses-material-design: true

  assets:
    - assets/programming_lang_png/
