name: interview_prep
description: A InterviewPrep App for preparing an interview.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # config
  go_router: ^12.1.0
  connectivity_plus: ^4.0.2

  # Firebase
  firebase_storage: ^11.2.1
  firebase_core: ^2.13.0
  cloud_firestore: ^4.7.1

  # cache manage
  flutter_cached_pdfview: ^0.4.2
  simple_app_cache_manager: ^0.0.2

  flutter_gen: ^5.3.0
  app_bar_with_search_switch: ^1.3.9
  
  # local
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  path_provider: ^2.0.14

  # native splash screen
  flutter_native_splash: ^2.2.19

  # state management
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

  # for Loading feature
  flutter_spinkit: ^5.2.0
  shimmer: ^3.0.0

  # app features
  share_plus: ^7.0.0
  rate_my_app: ^1.1.4
  rating_dialog: ^2.0.4
  store_redirect: ^2.0.1
  version_tracker: ^2.2.0

  google_fonts: ^4.0.4
  http: ^0.13.6

  workmanager: ^0.5.1
  flutter_local_notifications: ^15.1.1
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  flutter_gen_runner: ^5.3.0
  hive_generator: ^1.1.3
  build_runner: ^2.3.3

flutter_native_splash:
  color: "#202122"
  image: assets/app.png

flutter:

  uses-material-design: true

  assets:
    - assets/app.png
    - assets/image_data/
    - assets/questions_data/


  fonts:
    - family: Ubuntu-Regular
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
