name: flutter_interview_questions
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Firebase
  firebase_storage: ^11.2.0
  firebase_core: ^2.12.0
  cloud_firestore: ^4.7.0

  # work with PDF
  file_picker: ^5.3.0
  easy_pdf_viewer: ^1.0.6


  flutter_gen: ^5.3.0
  app_bar_with_search_switch: ^1.3.9
  
  # local database
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  path_provider: ^2.0.14

  # native splash screen
  flutter_native_splash: ^2.2.19

  # state management
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2

  google_fonts: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

  flutter_gen_runner: ^5.3.0
  hive_generator: ^1.1.3
  build_runner: ^2.3.3

flutter_native_splash:
  color: "#202122"
  image: assets/splash.png


flutter:


  uses-material-design: true

  assets:
    - assets/programming_lang_png/
    - assets/prg_lang/


  fonts:
    - family: Ubuntu-Regular
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf

