name: interview_helper
description: "A Interview Helper App for preparing an interview."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # config
  go_router: ^12.1.0
  connectivity_plus: ^5.0.2

  # Firebase
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  onesignal_flutter: ^5.0.4

  # extra widgets
  flutter_gen: ^5.3.0
  app_bar_with_search_switch: ^1.3.9
  flutter_onboarding_slider: ^1.0.11
  
  # local
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.1
  cached_network_image: ^3.3.0
  simple_app_cache_manager: ^0.0.4
  flutter_cache_manager: ^3.3.1
  flutter_pdfview: ^1.3.2

  # native
  flutter_native_splash: ^2.2.19

  # state management
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

  # animations
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0

  # app features
  share_plus: ^7.0.0
  rate_my_app: ^2.0.0
  rating_dialog: ^2.0.4
  store_redirect: ^2.0.1
  version_tracker: ^2.2.0

  auto_size_text: ^3.0.0
  google_fonts: ^6.1.0
  http: ^1.1.0

  # system packages
  path_provider: ^2.0.14
  permission_handler: ^11.1.0
  app_settings: ^5.1.1
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

  flutter_launcher_icons: ^0.13.1
  flutter_gen_runner: ^5.3.0
  hive_generator: ^2.0.1
  build_runner: ^2.3.3

flutter_launcher_icons:
  android: "launcher_icon"
  image_path_android: "assets/app-original.png"
  adaptive_icon_foreground: "assets/app-original.png"
  adaptive_icon_background: "#1398C3"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/app.png

flutter:

  uses-material-design: true

  assets:
     - assets/app.png
     - assets/app-original.png
     - assets/svg/
     - assets/icons/
     - assets/questions/
     - assets/introduction/


  fonts:
    - family: Ubuntu-Regular
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
