class Categories {
  static final List<String> categories = [
    'flutter',
    'go',
    'java',
    'python',
    'ruby',
    'rust',
    'js',
    'react',
    'csharp',
    'backend',
    'cplascplas',
    'cybersecurity',
    'dataanalyst',
    'datascientist',
    'engineer',
    'frontend',
    'git',
    'nodejs',
    'perl',
    'php',
    'scala',
    'swift',
  ];
}
